# Window effects
border_radius = 8

# Gaps
gappih = 10
gappiv = 10
gappoh = 10
gappov = 10
special_dim=0.5
special_gappi=24
special_gappo=48
overviewgappi = 24
overviewgappo = 48

# Animations
animations = 1
animation_duration_open = 400
animation_duration_close = 300

# Other appearance
borderpx = 2

# Mouse
cursor_theme = Bibata-Modern-Ice
cursor_size = 24
mouse_natural_scrolling = 0

# Touchpad
trackpad_natural_scrolling = 1
trackpad_disable_while_typing = 1

# Keyboard
repeat_rate = 35
repeat_delay = 200

# Layout
dwindle_hsplit = 1
tagrule=id:1,layout_name:dwindle
tagrule=id:2,layout_name:dwindle
tagrule=id:3,layout_name:dwindle
tagrule=id:4,layout_name:dwindle
tagrule=id:5,layout_name:dwindle
tagrule=id:6,layout_name:dwindle
tagrule=id:7,layout_name:dwindle
tagrule=id:8,layout_name:dwindle
tagrule=id:9,layout_name:dwindle
tagrule=id:0,layout_name:center_tile

# Windowrules
windowrule=special_tag:1,appid:vesktop
# windowrule=special_tag:true,appid:foot

# Environment Variables
env = QS_BAR,mangowc
env = QT_QPA_PLATFORM,wayland
env = ELECTRON_OZONE_PLATFORM_HINT,wayland
env = XCURSOR_THEME,Bibata-Modern-Ice
env = XCURSOR_SIZE,24

# Autostart
exec-once = systemctl --user import-environment WAYLAND_DISPLAY DISPLAY XDG_CURRENT_DESKTOP && systemctl --user start wayland-session.target
exec-once = QS_BAR=mangowc quickshell
exec-once = swaybg -i ~/Pictures/wallpaper -m fill
exec-once = sh -c "sleep 1; exec nm-applet --indicator"

source = ./colours.conf
source = ./binds.conf
