# Staged Quickshell module manifest for editor/LSP tooling only.
#
# This file is intentionally NOT named `qmldir`, because Quickshell
# resolves `pragma Singleton` types from the config directory without
# one, and adding a real `qmldir` risks changing (or breaking) that
# runtime registration. To use it for qmllint/qmlls, rename to `qmldir`
# in ~/.config/quickshell (or this directory) and restart your editor:
#     cp qmldir.lsp ~/.config/quickshell/qmldir
# Revert by deleting that copy.
#
# NOTE: Colours.qml is generated by Nix (Hjem) and only exists in the live
# ~/.config/quickshell directory, so this listing assumes it is present.

singleton Colours 1.0 Colours.qml
singleton Config 1.0 Config.qml
singleton MediaService 1.0 MediaService.qml
singleton NotificationStore 1.0 NotificationStore.qml
singleton WindowFocuser 1.0 WindowFocuser.qml

BatteryWidget 1.0 BatteryWidget.qml
BluetoothWidget 1.0 BluetoothWidget.qml
ClockWidget 1.0 ClockWidget.qml
CommandCentre 1.0 CommandCentre.qml
CommandCentreButton 1.0 CommandCentreButton.qml
HyprlandService 1.0 HyprlandService.qml
LayoutWidget 1.0 LayoutWidget.qml
LockScreen 1.0 LockScreen.qml
MangoService 1.0 MangoService.qml
MediaCard 1.0 MediaCard.qml
MediaProgressRow 1.0 MediaProgressRow.qml
MediaWidget 1.0 MediaWidget.qml
NetworkWidget 1.0 NetworkWidget.qml
NiriService 1.0 NiriService.qml
NotificationCard 1.0 NotificationCard.qml
NotificationOverlay 1.0 NotificationOverlay.qml
Pill 1.0 Pill.qml
PlaybackControls 1.0 PlaybackControls.qml
PowerButtons 1.0 PowerButtons.qml
RiverService 1.0 RiverService.qml
RoundedImage 1.0 RoundedImage.qml
SharedTooltipWindow 1.0 SharedTooltipWindow.qml
SliderControl 1.0 SliderControl.qml
Tooltip 1.0 Tooltip.qml
VolumeWidget 1.0 VolumeWidget.qml
WindowTitleWidget 1.0 WindowTitleWidget.qml
WmService 1.0 WmService.qml
WorkspacesWidget 1.0 WorkspacesWidget.qml
