# Window effects
blur = 0
blur_optimized = 1
blur_params_radius = 5
blur_params_num_passes = 2
border_radius = 8
focused_opacity = 1.0
unfocused_opacity = 1.0

# Gaps
gappih = 12
gappiv = 12
gappoh = 12
gappov = 12
overviewgappi = 24
overviewgappo = 48

# Animations
animations = 1
animation_duration_open = 400
animation_duration_close = 300

# Other appearance
borderpx = 2

# Mouse
mouse_natural_scrolling = 0

# Touchpad
trackpad_natural_scrolling = 1

# Keyboard
repeat_rate = 35
repeat_delay = 200

# Layout
dwindle_hsplit = 1

# Environment Variables
env = QS_BAR,mangowc
env = QT_QPA_PLATFORM,wayland
env = ELECTRON_OZONE_PLATFORM_HINT,wayland
env = XCURSOR_THEME,Bibata-Modern-Ice
env = XCURSOR_SIZE,24

# Autostart
exec-once = systemctl --user import-environment WAYLAND_DISPLAY DISPLAY XDG_CURRENT_DESKTOP && systemctl --user start wayland-session.target
exec-once = QS_BAR=mangowc quickshell
exec-once = swaybg -i ~/Pictures/wallpaper -m fill
exec-once = sh -c "sleep 1; exec nm-applet --indicator"

source = ./colours.conf
source = ./binds.conf
