local ls = require("luasnip")
local s = ls.snippet
local t = ls.text_node
local i = ls.insert_node
local c = ls.choice_node
local sn = ls.snippet_node

-- Helper for simple text wrapping
local function wrap(trig, open, close, desc)
	return s({ trig = trig, desc = desc }, {
		t(open),
		i(1),
		t(close),
	})
end

-- Helper for uniform callout blocks with icons, names, borders, and background fills
local function make_callout(trig, title, icon, color_hex, desc)
	return s({ trig = trig, desc = desc }, {
		t({
			'#block(',
			'\twidth: 100%,',
			'\tstroke: (left: 3.5pt + rgb("' .. color_hex .. '"), rest: 0.5pt + rgb("' .. color_hex .. '40")),',
			'\tfill: rgb("' .. color_hex .. '15"),',
			'\tinset: (x: 12pt, y: 10pt),',
			'\tradius: (right: 4pt),',
			'\t[',
			'\t\t#text(weight: "bold", fill: rgb("' .. color_hex .. '"))[' .. icon .. " " .. title .. ": ",
		}),
		i(1, "Title"),
		t({
			'] \\',
			'\t\t#v(2pt)',
			'\t\t',
		}),
		i(2, "Content..."),
		t({
			"",
			"\t]",
			")",
		}),
	})
end

-- Helper for language code blocks
local function make_codeblock(trig, lang, desc)
	return s({ trig = trig, desc = desc }, {
		t({ "```" .. lang, "" }),
		i(1),
		t({ "", "```" })
	})
end

ls.add_snippets("typst", {
	---------------------------------------------------------------------------
	-- BOILERPLATES & TEMPLATES
	---------------------------------------------------------------------------
	s({ trig = "page", desc = "Mathematical textbook style page boilerplate with dynamic theme variable" }, {
		t({ '#let theme = "' }),
		c(1, {
			sn(nil, { t("dark") }),
			sn(nil, { t("light") }),
		}),
		t({ '"', "" }),
		t({ ' #let bg-color = if theme == "dark" { rgb("#1a1a1a") } else { rgb("#ffffff") }', "" }),
		t({ ' #let text-color = if theme == "dark" { rgb("#e0e0e0") } else { rgb("#000000") }', "" }),
		t({ ' #let stroke-color = if theme == "dark" { rgb("#e0e0e0") } else { black }', "", "" }),
		t({ "#set page(", "" }),
		t({ '  paper: "a4",', "" }),
		t({ "  margin: (x: 2.5cm, top: 3cm, bottom: 3cm),", "" }),
		t({ "  fill: bg-color,", "" }),
		t({ "  header: context {", "" }),
		t({ "    let page_num = counter(page).get().first()", "" }),
		t({ "    if page_num > 1 {", "" }),
		t({ '      set text(size: 8.5pt, font: "New Computer Modern", fill: text-color)', "" }),
		t({ "      grid(", "" }),
		t({ "        columns: (1fr, 1fr, 1fr),", "" }),
		t({ "        align(left)[#smallcaps[Sec. 1.2]],", "" }),
		t({ "        align(center)[#smallcaps[Mathematical Language]],", "" }),
		t({ "        align(right)[#str(page_num)],", "" }),
		t({ "      )", "" }),
		t({ "    }", "" }),
		t({ "  },", "" }),
		t({ "  footer: context {", "" }),
		t({ "    let page_num = counter(page).get().first()", "" }),
		t({ "    if page_num == 1 or calc.even(page_num) {", "" }),
		t({ '      set text(size: 9pt, font: "New Computer Modern", fill: text-color)', "" }),
		t({ "      align(center)[#str(page_num)]", "" }),
		t({ "    }", "" }),
		t({ "  },", "" }),
		t({ ")", "", "" }),
		t({ '#set text(font: "New Computer Modern", size: 10pt, fill: text-color, lang: "en")', "" }),
		t({ "#set par(justify: true, leading: 0.65em, first-line-indent: 0pt)", "", "" }),
		t({ "// Level 1: Large italic chapter title", "" }),
		t({ "#show heading.where(level: 1): it => block(below: 2em)[", "" }),
		t({ '  #text(size: 22pt, weight: "regular", style: "italic", fill: text-color)[#it.body]', "" }),
		t({ "  #v(0.4em)", "" }),
		t({ '  #text(size: 11pt, weight: "regular", fill: text-color)[#smallcaps[Chapter 1]]', "" }),
		t({ "]", "", "" }),
		t({ "// Level 2: Bold small-caps section title with trailing line", "" }),
		t({ "#show heading.where(level: 2): it => block(above: 1.8em, below: 1.2em)[", "" }),
		t({ "  #box(baseline: 0%, [", "" }),
		t({ '    #text(weight: "bold", fill: text-color)[#smallcaps[#it.body]]', "" }),
		t({ "    #h(0.8em)", "" }),
		t({ "    #box(line(length: 6cm, stroke: 0.8pt + stroke-color))", "" }),
		t({ "  ])", "" }),
		t({ "]", "", "" }),
		t({ "// Underline links", "" }),
		t({ "#show link: underline", "", "" }),
		t({ "// Styled code blocks: actual background with language header bar", "" }),
		t({ "#show raw.where(block: true): it => {", "" }),
		t({ '  let lang = if it.lang != none { it.lang } else { "" }', "" }),
		t({ "  block(", "" }),
		t({ "    width: 100%,", "" }),
		t({ "    radius: 4pt,", "" }),
		t({ '    stroke: 0.5pt + (if theme == "dark" { rgb("#404040") } else { rgb("#d0d0d0") }),', "" }),
		t({ '    fill: if theme == "dark" { rgb("#242424") } else { rgb("#f8f9fa") },', "" }),
		t({ "    clip: true,", "" }),
		t({ "    [", "" }),
		t({ '      #if lang != "" [', "" }),
		t({ "        #block(", "" }),
		t({ "          width: 100%,", "" }),
		t({ '          fill: if theme == "dark" { rgb("#181818") } else { rgb("#eeeeee") },', "" }),
		t({ "          inset: (x: 10pt, y: 5pt),", "" }),
		t({ '          stroke: (bottom: 0.5pt + (if theme == "dark" { rgb("#383838") } else { rgb("#d0d0d0") })),', "" }),
		t({ "          [", "" }),
		t({ '            #text(size: 8pt, weight: "bold", fill: if theme == "dark" { rgb("#a0a0a0") } else { rgb("#666666") })[#upper(lang)]', "" }),
		t({ "          ]", "" }),
		t({ "        )", "" }),
		t({ "      ]", "" }),
		t({ "      #block(inset: (x: 10pt, y: 8pt))[", "" }),
		t({ "        #set text(fill: text-color)", "" }),
		t({ "        #it", "" }),
		t({ "      ]", "" }),
		t({ "    ]", "" }),
		t({ "  )", "" }),
		t({ "}", "", "" }),
		t({ "// Inline code styling", "" }),
		t({ "#show raw.where(block: false): it => box(", "" }),
		t({ '  fill: if theme == "dark" { rgb("#2a2a2a") } else { rgb("#f0f0f0") },', "" }),
		t({ "  inset: (x: 3.5pt, y: 1.5pt),", "" }),
		t({ "  baseline: 0%,", "" }),
		t({ "  radius: 3pt,", "" }),
		t({ '  stroke: 0.4pt + (if theme == "dark" { rgb("#404040") } else { rgb("#d0d0d0") }),', "" }),
		t({ "  text(size: 0.9em, it)", "" }),
		t({ ")", "", "" }),
		t({ "= " }),
		i(2, "Mathematical Language"),
		t({ "", "", "== " }),
		i(3, "1.1. Sets"),
		t({ "", "", "" }),
		i(4, "Content here..."),
	}),

	s({ trig = "lecture", desc = "University lecture notes template with dynamic theme variable" }, {
		t({ '#let theme = "' }),
		c(1, {
			sn(nil, { t("dark") }),
			sn(nil, { t("light") }),
		}),
		t({ '"', "" }),
		t({ ' #let bg-color = if theme == "dark" { rgb("#1a1a1a") } else { rgb("#ffffff") }', "" }),
		t({ ' #let text-color = if theme == "dark" { rgb("#e0e0e0") } else { rgb("#000000") }', "" }),
		t({ ' #let stroke-color = if theme == "dark" { rgb("#e0e0e0") } else { black }', "", "" }),
		t({ "#set page(", "" }),
		t({ '  paper: "a4",', "" }),
		t({ "  margin: (x: 2.5cm, top: 3cm, bottom: 3cm),", "" }),
		t({ "  fill: bg-color,", "" }),
		t({ "  footer: context {", "" }),
		t({ "    let page_num = counter(page).get().first()", "" }),
		t({ '    set text(size: 9pt, font: "New Computer Modern", fill: text-color)', "" }),
		t({ "    align(center)[#str(page_num)]", "" }),
		t({ "  },", "" }),
		t({ ")", "", "" }),
		t({ '#set text(font: "New Computer Modern", size: 10pt, fill: text-color, lang: "en")', "" }),
		t({ "#set par(justify: true, leading: 0.65em, first-line-indent: 0pt)", "", "" }),
		t({ "// Level 1: Heading with line rule", "" }),
		t({ "#show heading.where(level: 1): it => block(below: 1.2em)[", "" }),
		t({ '  #text(size: 16pt, weight: "bold", fill: text-color)[#it.body]', "" }),
		t({ "  #v(0.3em)", "" }),
		t({ '  #line(length: 100%, stroke: 1.2pt + stroke-color)', "" }),
		t({ "]", "", "" }),
		t({ "// Level 2: Bold small-caps section title with trailing line", "" }),
		t({ "#show heading.where(level: 2): it => block(above: 1.8em, below: 1.2em)[", "" }),
		t({ "  #box(baseline: 0%, [", "" }),
		t({ '    #text(weight: "bold", fill: text-color)[#smallcaps[#it.body]]', "" }),
		t({ "    #h(0.8em)", "" }),
		t({ "    #box(line(length: 6cm, stroke: 0.8pt + stroke-color))", "" }),
		t({ "  ])", "" }),
		t({ "]", "", "" }),
		t({ "// Underline links", "" }),
		t({ "#show link: underline", "", "" }),
		t({ "// Styled code blocks: actual background with language header bar", "" }),
		t({ "#show raw.where(block: true): it => {", "" }),
		t({ '  let lang = if it.lang != none { it.lang } else { "" }', "" }),
		t({ "  block(", "" }),
		t({ "    width: 100%,", "" }),
		t({ "    radius: 4pt,", "" }),
		t({ '    stroke: 0.5pt + (if theme == "dark" { rgb("#404040") } else { rgb("#d0d0d0") }),', "" }),
		t({ '    fill: if theme == "dark" { rgb("#242424") } else { rgb("#f8f9fa") },', "" }),
		t({ "    clip: true,", "" }),
		t({ "    [", "" }),
		t({ '      #if lang != "" [', "" }),
		t({ "        #block(", "" }),
		t({ "          width: 100%,", "" }),
		t({ '          fill: if theme == "dark" { rgb("#181818") } else { rgb("#eeeeee") },', "" }),
		t({ "          inset: (x: 10pt, y: 5pt),", "" }),
		t({ '          stroke: (bottom: 0.5pt + (if theme == "dark" { rgb("#383838") } else { rgb("#d0d0d0") })),', "" }),
		t({ "          [", "" }),
		t({ '            #text(size: 8pt, weight: "bold", fill: if theme == "dark" { rgb("#a0a0a0") } else { rgb("#666666") })[#upper(lang)]', "" }),
		t({ "          ]", "" }),
		t({ "        )", "" }),
		t({ "      ]", "" }),
		t({ "      #block(inset: (x: 10pt, y: 8pt))[", "" }),
		t({ "        #set text(fill: text-color)", "" }),
		t({ "        #it", "" }),
		t({ "      ]", "" }),
		t({ "    ]", "" }),
		t({ "  )", "" }),
		t({ "}", "", "" }),
		t({ "// Inline code styling", "" }),
		t({ "#show raw.where(block: false): it => box(", "" }),
		t({ '  fill: if theme == "dark" { rgb("#2a2a2a") } else { rgb("#f0f0f0") },', "" }),
		t({ "  inset: (x: 3.5pt, y: 1.5pt),", "" }),
		t({ "  baseline: 0%,", "" }),
		t({ "  radius: 3pt,", "" }),
		t({ '  stroke: 0.4pt + (if theme == "dark" { rgb("#404040") } else { rgb("#d0d0d0") }),', "" }),
		t({ "  text(size: 0.9em, it)", "" }),
		t({ ")", "", "" }),
		t({ "#align(center)[", "" }),
		t({ '  #text(size: 20pt, weight: "bold", fill: text-color)[' }),
		i(2, "COMPX201: Lecture Title"),
		t({ "]", "", "" }),
		t({ '  #text(size: 10pt, fill: text-color)[' }),
		i(3, "Date: " .. os.date("%d %B %Y")),
		t({ "]", "", "]", "", "" }),
		t("= "),
		i(4, "Overview"),
		t({ "", "", "" }),
		i(5),
	}),

	---------------------------------------------------------------------------
	-- NOTE BLOCKS & CALLOUTS (With icons, names, and background fills)
	---------------------------------------------------------------------------
	make_callout("note", "Note", "📝", "#3182ce", "Note callout box with blue border, 📝 icon, and background fill"),
	make_callout("info", "Info", "ℹ", "#3182ce", "Info callout box with blue border, ℹ icon, and background fill"),
	make_callout("tip", "Tip", "💡", "#38a169", "Tip callout box with green border, 💡 icon, and background fill"),
	make_callout("warn", "Warning", "⚠", "#dd6b20", "Warning callout box with orange border, ⚠ icon, and background fill"),
	make_callout("warning", "Warning", "⚠", "#dd6b20", "Warning callout box (alias)"),
	make_callout("caution", "Caution", "🚨", "#e53e3e", "Caution callout box with red border, 🚨 icon, and background fill"),
	make_callout("danger", "Danger", "🛑", "#e53e3e", "Danger callout box with red border, 🛑 icon, and background fill"),
	make_callout("important", "Important", "❗", "#e53e3e", "Important callout box with red border, ❗ icon, and background fill"),
	make_callout("def", "Definition", "📖", "#3182ce", "Definition container box with blue border, 📖 icon, and background fill"),
	make_callout("definition", "Definition", "📖", "#3182ce", "Definition container box (alias)"),
	make_callout("thm", "Theorem", "📐", "#38a169", "Theorem container box with green border, 📐 icon, and background fill"),
	make_callout("theorem", "Theorem", "📐", "#38a169", "Theorem container box (alias)"),
	make_callout("lem", "Lemma", "🧩", "#805ad5", "Lemma container box with purple border, 🧩 icon, and background fill"),
	make_callout("lemma", "Lemma", "🧩", "#805ad5", "Lemma container box (alias)"),
	make_callout("cor", "Corollary", "📎", "#3182ce", "Corollary container box with blue border, 📎 icon, and background fill"),
	make_callout("corollary", "Corollary", "📎", "#3182ce", "Corollary container box (alias)"),
	make_callout("prop", "Proposition", "💡", "#3182ce", "Proposition container box with blue border, 💡 icon, and background fill"),
	make_callout("ex", "Example", "✏", "#dd6b20", "Example container box with orange border, ✏ icon, and background fill"),
	make_callout("example", "Example", "✏", "#dd6b20", "Example container box (alias)"),
	make_callout("question", "Question", "❓", "#805ad5", "Question container box with purple border, ❓ icon, and background fill"),
	make_callout("prob", "Problem", "❓", "#805ad5", "Problem container box with purple border, ❓ icon, and background fill"),
	make_callout("sol", "Solution", "💡", "#38a169", "Solution container box with green border, 💡 icon, and background fill"),
	make_callout("rem", "Remark", "💬", "#718096", "Remark container box with grey border, 💬 icon, and background fill"),
	make_callout("remark", "Remark", "💬", "#718096", "Remark container box (alias)"),
	make_callout("key", "Key Takeaway", "📌", "#dd6b20", "Key Takeaway callout box with orange border, 📌 icon, and background fill"),
	make_callout("takeaway", "Key Takeaway", "📌", "#dd6b20", "Key Takeaway callout box (alias)"),

	-- Proof block
	s({ trig = "proof", desc = "Mathematical proof block with QED square" }, {
		t({
			'#block(',
			'\twidth: 100%,',
			'\tstroke: (left: 2.5pt + rgb("#718096"), rest: 0.5pt + rgb("#71809630")),',
			'\tfill: rgb("#71809612"),',
			'\tinset: (x: 12pt, y: 10pt),',
			'\tradius: (right: 4pt),',
			'\t[',
			'\t\t#text(weight: "bold", fill: rgb("#718096"))[∎ Proof:] \\',
			'\t\t#v(2pt)',
			'\t\t',
		}),
		i(1, "Proof body..."),
		t({
			" #h(1fr) $square$",
			"",
			"\t]",
			")",
		}),
	}),

	-- Modern styled callout alert box with selectable colors
	s({ trig = "callout", desc = "Modern styled callout alert box with icon and background fill" }, {
		t("#block(stroke: (left: 3.5pt + rgb("),
		c(1, {
			sn(nil, { t('"#3182ce"') }),
			sn(nil, { t('"#38a169"') }),
			sn(nil, { t('"#dd6b20"') }),
			sn(nil, { t('"#e53e3e"') }),
			sn(nil, { t('"#805ad5"') }),
		}),
		t('), rest: 0.5pt + rgb("'),
		c(2, {
			sn(nil, { t("#3182ce40") }),
			sn(nil, { t("#38a16940") }),
			sn(nil, { t("#dd6b2040") }),
			sn(nil, { t("#e53e3e40") }),
			sn(nil, { t("#805ad540") }),
		}),
		t('")), fill: rgb("'),
		c(3, {
			sn(nil, { t("#3182ce15") }),
			sn(nil, { t("#38a16915") }),
			sn(nil, { t("#dd6b2015") }),
			sn(nil, { t("#e53e3e15") }),
			sn(nil, { t("#805ad515") }),
		}),
		t('"), inset: (x: 12pt, y: 10pt), radius: (right: 4pt), width: 100%)[\n  #text(weight: "bold")['),
		i(4, "ℹ Info: Title"),
		t({ "] \\\n  #v(2pt)\n  " }),
		i(5, "Body content..."),
		t({ "", "]" }),
	}),

	---------------------------------------------------------------------------
	-- CODE BLOCKS (With background and language headers)
	---------------------------------------------------------------------------
	-- Code block show rule to drop into any file
	s({ trig = "codeshow", desc = "Insert #show raw rule for code block background & language header" }, {
		t({
			"// Styled code blocks: actual background with language header bar",
			"#show raw.where(block: true): it => {",
			'  let lang = if it.lang != none { it.lang } else { "" }',
			"  block(",
			"    width: 100%,",
			"    radius: 4pt,",
			'    stroke: 0.5pt + (if theme == "dark" { rgb("#404040") } else { rgb("#d0d0d0") }),',
			'    fill: if theme == "dark" { rgb("#242424") } else { rgb("#f8f9fa") },',
			"    clip: true,",
			"    [",
			'      #if lang != "" [',
			"        #block(",
			"          width: 100%,",
			'          fill: if theme == "dark" { rgb("#181818") } else { rgb("#eeeeee") },',
			"          inset: (x: 10pt, y: 5pt),",
			'          stroke: (bottom: 0.5pt + (if theme == "dark" { rgb("#383838") } else { rgb("#d0d0d0") })),',
			"          [",
			'            #text(size: 8pt, weight: "bold", fill: if theme == "dark" { rgb("#a0a0a0") } else { rgb("#666666") })[#upper(lang)]',
			"          ]",
			"        )",
			"      ]",
			"      #block(inset: (x: 10pt, y: 8pt))[",
			"        #set text(fill: text-color)",
			"        #it",
			"      ]",
			"    ]",
			"  )",
			"}",
			"",
			"// Inline code styling",
			"#show raw.where(block: false): it => box(",
			'  fill: if theme == "dark" { rgb("#2a2a2a") } else { rgb("#f0f0f0") },',
			"  inset: (x: 3.5pt, y: 1.5pt),",
			"  baseline: 0%,",
			"  radius: 3pt,",
			'  stroke: 0.4pt + (if theme == "dark" { rgb("#404040") } else { rgb("#d0d0d0") }),',
			"  text(size: 0.9em, it)",
			")",
		}),
	}),
	s({ trig = "rawshow", desc = "Insert #show raw rule (alias)" }, {
		t({
			"#show raw.where(block: true): it => {",
			'  let lang = if it.lang != none { it.lang } else { "" }',
			"  block(",
			"    width: 100%,",
			"    radius: 4pt,",
			'    stroke: 0.5pt + (if theme == "dark" { rgb("#404040") } else { rgb("#d0d0d0") }),',
			'    fill: if theme == "dark" { rgb("#242424") } else { rgb("#f8f9fa") },',
			"    clip: true,",
			"    [",
			'      #if lang != "" [',
			"        #block(",
			"          width: 100%,",
			'          fill: if theme == "dark" { rgb("#181818") } else { rgb("#eeeeee") },',
			"          inset: (x: 10pt, y: 5pt),",
			'          stroke: (bottom: 0.5pt + (if theme == "dark" { rgb("#383838") } else { rgb("#d0d0d0") })),',
			"          [",
			'            #text(size: 8pt, weight: "bold", fill: if theme == "dark" { rgb("#a0a0a0") } else { rgb("#666666") })[#upper(lang)]',
			"          ]",
			"        )",
			"      ]",
			"      #block(inset: (x: 10pt, y: 8pt))[#it]",
			"    ]",
			"  )",
			"}",
		}),
	}),

	-- Code block with filename header banner
	s({ trig = "cbf", desc = "Code block container with filename header banner" }, {
		t({
			"#block(",
			"  width: 100%,",
			"  radius: 4pt,",
			'  stroke: 0.5pt + stroke-color,',
			'  fill: if theme == "dark" { rgb("#242424") } else { rgb("#f8f9fa") },',
			"  clip: true,",
			"  [",
			"    #block(",
			"      width: 100%,",
			'      fill: if theme == "dark" { rgb("#181818") } else { rgb("#eeeeee") },',
			"      inset: (x: 10pt, y: 5pt),",
			'      stroke: (bottom: 0.5pt + stroke-color),',
			"      [",
			"        #grid(",
			"          columns: (1fr, auto),",
			'          [#text(size: 8.5pt, weight: "bold")[📄 ',
		}),
		i(1, "filename.ext"),
		t({
			"]],",
			'          [#text(size: 7.5pt, weight: "bold")[#upper("',
		}),
		i(2, "lang"),
		t({
			'")]],',
			"        )",
			"      ]",
			"    )",
			"    ```",
		}),
		i(3, "lang"),
		t({ "", "" }),
		i(4),
		t({ "", "    ```", "  ]", ")" }),
	}),

	s({ trig = "ic", desc = "Inline monospaced code snippet" }, { t("`"), i(1, "code"), t("`") }),
	s({ trig = "cb", desc = "Code block container with dynamic language identifier" }, {
		t("```"),
		i(1, "lang"),
		t({ "", "" }),
		i(2),
		t({ "", "```" }),
	}),
	s({ trig = "```", desc = "Raw typst interpretation text block container" }, {
		t("```"),
		i(1, "typ"),
		t({ "", "" }),
		i(2),
		t({ "", "```" }),
	}),
	s({ trig = "raw", desc = "Raw unhighlighted code text block container" }, {
		t({ "```", "" }),
		i(1),
		t({ "", "```" }),
	}),

	-- Language-specific code blocks
	make_codeblock("cbpy", "py", "Code block specified for Python code syntax"),
	make_codeblock("cbsql", "sql", "Code block specified for SQL database query syntax"),
	make_codeblock("cbv", "verilog", "Code block specified for Verilog HDL syntax"),
	make_codeblock("cbverilog", "verilog", "Code block specified for Verilog HDL syntax (alias)"),
	make_codeblock("cbjava", "java", "Code block specified for Java code syntax"),
	make_codeblock("cbc", "c", "Code block specified for C programming language syntax"),
	make_codeblock("cbcpp", "cpp", "Code block specified for C++ programming language syntax"),
	make_codeblock("cbrs", "rust", "Code block specified for Rust code syntax"),
	make_codeblock("cbjs", "js", "Code block specified for JavaScript code syntax"),
	make_codeblock("cbts", "ts", "Code block specified for TypeScript code syntax"),
	make_codeblock("cbsh", "sh", "Code block specified for Shell script programming syntax"),
	make_codeblock("cbbash", "bash", "Code block specified for Bash syntax (alias)"),
	make_codeblock("cbnix", "nix", "Code block specified for Nix package configuration syntax"),
	make_codeblock("cblua", "lua", "Code block specified for Lua configuration script syntax"),
	make_codeblock("cbtyp", "typ", "Code block specified for Typst markup syntax"),
	make_codeblock("cbasm", "asm", "Code block specified for Assembly / RISC-V syntax"),
	make_codeblock("cbhtml", "html", "Code block specified for HTML markup language syntax"),
	make_codeblock("cbcss", "css", "Code block specified for CSS presentational language syntax"),
	make_codeblock("cbjson", "json", "Code block specified for JSON data syntax"),
	make_codeblock("cbgo", "go", "Code block specified for Go programming syntax"),
	make_codeblock("cbhs", "hs", "Code block specified for Haskell functional language syntax"),

	---------------------------------------------------------------------------
	-- LINKS & REFERENCES (With automatic underlines)
	---------------------------------------------------------------------------
	s({ trig = "lnk", desc = "Hyperlink with custom display text (underlined)" }, {
		t('#link("'),
		i(1, "url"),
		t('")['),
		i(2, "text"),
		t("]"),
	}),
	s({ trig = "url", desc = "Clickable hyperlink URL (underlined)" }, {
		t('#link("'),
		i(1, "url"),
		t('")'),
	}),
	s({ trig = "linkshow", desc = "Insert #show link underline rule" }, {
		t("#show link: underline"),
	}),

	---------------------------------------------------------------------------
	-- NOTE TAKING ESSENTIALS: STEPS, LISTS, TERMS, BADGES, CARDS
	---------------------------------------------------------------------------
	s({ trig = "step", desc = "Numbered procedure step" }, {
		t("+ *Step "),
		i(1, "1"),
		t(":* "),
		i(2, "Description"),
	}),
	s({ trig = "steps", desc = "3-step procedural checklist" }, {
		t("+ *Step 1:* "),
		i(1, "First step"),
		t({ "", "+ *Step 2:* " }),
		i(2, "Second step"),
		t({ "", "+ *Step 3:* " }),
		i(3, "Third step"),
	}),
	s({ trig = "kv", desc = "Key-value / term definition pair" }, {
		t("*"),
		i(1, "Term"),
		t(":* "),
		i(2, "Definition"),
		t("\\"),
	}),
	s({ trig = "term", desc = "Term definition with dash separator" }, {
		t("*"),
		i(1, "Term"),
		t("* -- "),
		i(2, "Description"),
	}),
	s({ trig = "badge", desc = "Inline colored pill badge / tag" }, {
		t('#box(fill: rgb("'),
		c(1, {
			sn(nil, { t("#3182ce20") }),
			sn(nil, { t("#38a16920") }),
			sn(nil, { t("#dd6b2020") }),
			sn(nil, { t("#e53e3e20") }),
			sn(nil, { t("#805ad520") }),
		}),
		t('"), inset: (x: 5pt, y: 2pt), radius: 3pt)[#text(size: 8pt, weight: "bold", fill: rgb("'),
		c(2, {
			sn(nil, { t("#3182ce") }),
			sn(nil, { t("#38a169") }),
			sn(nil, { t("#dd6b20") }),
			sn(nil, { t("#e53e3e") }),
			sn(nil, { t("#805ad5") }),
		}),
		t('"))['),
		i(3, "TAG"),
		t("]]"),
	}),
	s({ trig = "qa", desc = "Question and Answer study block" }, {
		t({ '*Q:* #text(weight: "bold")[' }),
		i(1, "Question?"),
		t({ "] \\", "*A:* " }),
		i(2, "Answer"),
	}),
	s({ trig = "card", desc = "Bordered content card container" }, {
		t({
			'#block(width: 100%, stroke: 0.6pt + stroke-color, fill: if theme == "dark" { rgb("#242424") } else { rgb("#f8f9fa") }, inset: 12pt, radius: 4pt)[',
			"\t",
		}),
		i(1, "Content..."),
		t({ "", "]" }),
	}),
	s({ trig = "box", desc = "Simple padded container box" }, {
		t({ '#box(stroke: 0.8pt + stroke-color, inset: 10pt, radius: 4pt, width: 100%)[', "\t" }),
		i(1, "Content..."),
		t({ "", "]" }),
	}),
	s({ trig = "todo", desc = "Incomplete checkbox todo list item" }, { t("- [ ] "), i(1) }),
	s({ trig = "done", desc = "Completed checkbox todo list item" }, { t("- [x] "), i(1) }),
	s({ trig = "quote", desc = "Attributed blockquote element" }, {
		t('#quote(attribution: ['),
		i(1, "Author / Source"),
		t({ "])[", "\t" }),
		i(2, "Quote text..."),
		t({ "", "]" }),
	}),
	s({ trig = "date", desc = "Insert current date string" }, {
		t(os.date("%d %B %Y")),
	}),
	s({ trig = "hr", desc = "Horizontal divider rule line" }, {
		t('#line(length: 100%, stroke: 0.6pt + stroke-color)'),
	}),
	s({ trig = "divider", desc = "Horizontal divider rule line (alias)" }, {
		t('#line(length: 100%, stroke: 0.6pt + stroke-color)'),
	}),

	---------------------------------------------------------------------------
	-- TABLES
	---------------------------------------------------------------------------
	s({ trig = "tbl", desc = "2-column formatted table with styled header fill" }, {
		t({
			"#table(",
			"  columns: (1fr, 1fr),",
			'  fill: (col, row) => if row == 0 { rgb("#3182ce18") } else { none },',
			"  stroke: 0.5pt + stroke-color,",
			"  [*",
		}),
		i(1, "Header 1"),
		t("*], [*"),
		i(2, "Header 2"),
		t({ "*],", "  [" }),
		i(3, "Row 1 Cell 1"),
		t("], ["),
		i(4, "Row 1 Cell 2"),
		t({ "],", "  [" }),
		i(5, "Row 2 Cell 1"),
		t("], ["),
		i(6, "Row 2 Cell 2"),
		t({ "],", ")" }),
	}),
	s({ trig = "tbl3", desc = "3-column formatted table with styled header fill" }, {
		t({
			"#table(",
			"  columns: (1fr, 1fr, 1fr),",
			'  fill: (col, row) => if row == 0 { rgb("#3182ce18") } else { none },',
			"  stroke: 0.5pt + stroke-color,",
			"  [*",
		}),
		i(1, "Header 1"),
		t("*], [*"),
		i(2, "Header 2"),
		t("*], [*"),
		i(3, "Header 3"),
		t({ "*],", "  [" }),
		i(4, "Row 1 Cell 1"),
		t("], ["),
		i(5, "Row 1 Cell 2"),
		t("], ["),
		i(6, "Row 1 Cell 3"),
		t({ "],", "  [" }),
		i(7, "Row 2 Cell 1"),
		t("], ["),
		i(8, "Row 2 Cell 2"),
		t("], ["),
		i(9, "Row 2 Cell 3"),
		t({ "],", ")" }),
	}),
	s({ trig = "tbl4", desc = "4-column formatted table with styled header fill" }, {
		t({
			"#table(",
			"  columns: (1fr, 1fr, 1fr, 1fr),",
			'  fill: (col, row) => if row == 0 { rgb("#3182ce18") } else { none },',
			"  stroke: 0.5pt + stroke-color,",
			"  [*",
		}),
		i(1, "Col 1"),
		t("*], [*"),
		i(2, "Col 2"),
		t("*], [*"),
		i(3, "Col 3"),
		t("*], [*"),
		i(4, "Col 4"),
		t({ "*],", "  [" }),
		i(5, "R1C1"),
		t("], ["),
		i(6, "R1C2"),
		t("], ["),
		i(7, "R1C3"),
		t("], ["),
		i(8, "R1C4"),
		t({ "],", ")" }),
	}),
	s({ trig = "truthtable", desc = "Formatted digital logic truth table" }, {
		t({
			"#table(",
			"  columns: (1fr, 1fr, 1fr),",
			"  align: center + horizon,",
			'  fill: (col, row) => if row < 2 { rgb("#3182ce18") } else { none },',
			"  stroke: 0.5pt + stroke-color,",
			"  table.cell(colspan: 2)[*INPUT*],",
			"  table.cell(rowspan: 2)[*OUTPUT*],",
			"  [*A*], [*B*],",
			"  [0], [0], [",
		}),
		i(1, "0"),
		t({ "],", "  [0], [1], [" }),
		i(2, "0"),
		t({ "],", "  [1], [0], [" }),
		i(3, "0"),
		t({ "],", "  [1], [1], [" }),
		i(4, "1"),
		t({ "],", ")" }),
	}),

	---------------------------------------------------------------------------
	-- FIGURES, MEDIA & DIAGRAMS
	---------------------------------------------------------------------------
	s({ trig = "fig", desc = "Figure block with embedded image and caption" }, {
		t("#figure("),
		t({ "", '  image("' }),
		i(1, "path"),
		t('", width: '),
		i(2, "80%"),
		t("),"),
		t({ "", "  caption: [" }),
		i(3, "Caption"),
		t("],"),
		t({ "", ")" }),
	}),
	s({ trig = "img", desc = "Image insertion element" }, {
		t('#image("'),
		i(1, "path"),
		t('", width: '),
		i(2, "100%"),
		t(")"),
	}),
	s({ trig = "gridimg", desc = "Two figures side-by-side in a grid" }, {
		t({
			"#grid(",
			"  columns: (1fr, 1fr),",
			"  gutter: 12pt,",
			'  figure(image("',
		}),
		i(1, "image1.png"),
		t('"), caption: ['),
		i(2, "Caption 1"),
		t({ "]),", '  figure(image("' }),
		i(3, "image2.png"),
		t('"), caption: ['),
		i(4, "Caption 2"),
		t({ "]),", ")" }),
	}),
	s({ trig = "circuit", desc = "CeTZ & Zap digital logic circuit diagram" }, {
		t({ "#zap.circuit({", "" }),
		t({ "  import zap: *", "" }),
		t({ '  cetz.draw.set-style(zap: (variant: "ieee"))', "" }),
		t({ '  node("A", (0, 0.2), label: (content: "A", anchor: "west", distance: 2pt))', "" }),
		t({ '  node("B", (0, -0.2), label: (content: "B", anchor: "west", distance: 2pt))', "" }),
		t({ '  node("C", (2, 0), label: (content: "C", anchor: "east", distance: 2pt))', "" }),
		t({ '  land("and1", (1, 0), label: "AND")', "" }),
		t({ '  wire("A", "and1.in1", anchor: "east")', "" }),
		t({ '  wire("B", "and1.in2", anchor: "east")', "" }),
		t({ '  wire("and1.out", "C", anchor: "west")', "" }),
		t({ "})" }),
	}),
	s({ trig = "cetz", desc = "CeTZ Canvas drawing container" }, {
		t({ "#cetz.canvas({", "  import cetz.draw: *", "  " }),
		i(1, '// draw.line((0, 0), (2, 2))\n  // draw.circle((1, 1), radius: 0.5)'),
		t({ "", "})" }),
	}),
	s({ trig = "erd", desc = "Mermaid Entity-Relationship Diagram (Database design)" }, {
		t({ "#mermaid(", "" }),
		t({ '  "erDiagram', "" }),
		t({ "  " }),
		i(
			1,
			"ENTITY_ONE {\n    int id PK\n    string name\n  }\n\n"
				.. "  ENTITY_TWO {\n    int id PK\n    int entity_one_id FK\n  }\n\n"
				.. "  ENTITY_ONE ||--o{ ENTITY_TWO : HAS"
		),
		t({ '\n"', "" }),
		t({ ")" }),
	}),
	s({ trig = "gantt", desc = "Mermaid Gantt chart (Project planning)" }, {
		t({ "#mermaid(", '  "gantt\n  dateFormat YYYY-MM-DD\n  title ' }),
		i(1, "Project Schedule"),
		t({ '\n  section Phase 1\n  Design : 2026-09-01, 7d\n  Coding : 2026-09-08, 14d\n"' }),
		t({ ")" }),
	}),
	s({ trig = "mmd", desc = "Mermaid Diagram wrapper" }, {
		t({ "#mermaid(", "" }),
		t({ '  "', "" }),
		t({ "  " }),
		i(
			1,
			"graph TD\n    A[Start] --> B(Process)\n    B --> C{Decision}\n    C -->|Yes| D[Result 1]\n    C -->|No| E[Result 2]"
		),
		t({ '\n"', "" }),
		t({ ")" }),
	}),
	s({ trig = "bigo", desc = "Data Structures & Algorithms Big-O Complexity Card" }, {
		t({ '#block(stroke: 1pt + rgb("#3182ce"), fill: rgb("#3182ce12"), inset: 10pt, radius: 4pt, width: 100%)[', "" }),
		t({ '  #text(weight: "bold", size: 12pt, fill: rgb("#3182ce"))[⚡ Big-O: ' }),
		i(1, "Algorithm / Data Structure Name"),
		t({ "]", "" }),
		t({ "  #v(0.4em)", "" }),
		t({ "  #grid(", "" }),
		t({ "    columns: (1fr, 1fr),", "" }),
		t({ "    [*Time Complexity:*], [*Space Complexity:*],", "" }),
		t({ "    [- Access: $" }),
		i(2, "O(1)"),
		t({ "$], [- Aux Space: $" }),
		i(5, "O(1)"),
		t({ "$],", "" }),
		t({ "    [- Search: $" }),
		i(3, "O(n)"),
		t({ "$], [],", "" }),
		t({ "    [- Insert/Delete: $" }),
		i(4, "O(1)"),
		t({ "$], [],", "" }),
		t({ "  )", "" }),
		t({ "]" }),
	}),

	---------------------------------------------------------------------------
	-- HEADINGS & LAYOUT
	---------------------------------------------------------------------------
	s({ trig = "h1", desc = "Heading level 1" }, { t("= "), i(1, "Heading") }),
	s({ trig = "h2", desc = "Heading level 2" }, { t("== "), i(1, "Heading") }),
	s({ trig = "h3", desc = "Heading level 3" }, { t("=== "), i(1, "Heading") }),
	s({ trig = "h4", desc = "Heading level 4" }, { t("==== "), i(1, "Heading") }),
	s({ trig = "h5", desc = "Heading level 5" }, { t("===== "), i(1, "Heading") }),
	s({ trig = "col", desc = "Multi-column layout block" }, {
		t("#columns("),
		i(1, "2"),
		t(")["),
		t({ "", "\t" }),
		i(2),
		t({ "", "]" }),
	}),
	s({ trig = "cols", desc = "Multi-column layout block (alias)" }, {
		t("#columns("),
		i(1, "2"),
		t(")["),
		t({ "", "\t" }),
		i(2),
		t({ "", "]" }),
	}),
	s({ trig = "col3", desc = "3-column layout block" }, {
		t("#columns(3)["),
		t({ "", "\t" }),
		i(1),
		t({ "", "]" }),
	}),
	s({ trig = "colbreak", desc = "Column break" }, { t("#colbreak()") }),
	s({ trig = "pagebreak", desc = "Page break" }, { t("#pagebreak()") }),
	s({ trig = "align", desc = "Content alignment block (center, left, right)" }, {
		t("#align("),
		c(1, {
			sn(nil, { t("center") }),
			sn(nil, { t("left") }),
			sn(nil, { t("right") }),
		}),
		t(")["),
		t({ "", "\t" }),
		i(2),
		t({ "", "]" }),
	}),
	s({ trig = "grid", desc = "2-column grid layout" }, {
		t({ "#grid(", "  columns: (1fr, 1fr),", "  gutter: 10pt,", "  [" }),
		i(1, "Left column"),
		t({ "],", "  [" }),
		i(2, "Right column"),
		t({ "],", ")" }),
	}),

	---------------------------------------------------------------------------
	-- TEXT FORMATTING
	---------------------------------------------------------------------------
	wrap("bf", "*", "*", "Bold text format"),
	wrap("it", "_", "_", "Italic text format"),
	wrap("st", "#strike[", "]", "Strikethrough text format"),
	wrap("hl", "#highlight[", "]", "Highlight text background"),
	wrap("sc", "#smallcaps[", "]", "Small caps text format"),
	wrap("sup", "#super[", "]", "Superscript text"),
	wrap("sub", "#sub[", "]", "Subscript text"),

	---------------------------------------------------------------------------
	-- MATHEMATICS
	---------------------------------------------------------------------------
	s({ trig = "$", desc = "Inline math block" }, { t("$"), i(1), t("$") }),
	s({ trig = "$$", desc = "Display math block" }, { t("$ "), i(1), t(" $") }),
	s({ trig = "eq", desc = "Multi-line block equation syntax" }, {
		t({ "$ " }),
		i(1),
		t({ " \\", "  " }),
		i(2),
		t({ " \\", "  " }),
		i(3),
		t({ " $" }),
	}),
	s({ trig = "eqalign", desc = "Aligned block equation structure using ampersand relations" }, {
		t({ "$ " }),
		i(1),
		t(" &="),
		i(2),
		t({ " \\", "  " }),
		i(3),
		t(" &="),
		i(4),
		t({ " $" }),
	}),

	s({ trig = "frac", desc = "Mathematical fraction symbol" }, { t("("), i(1, "num"), t(")/("), i(2, "den"), t(")") }),
	s(
		{ trig = "sum", desc = "Mathematical summation operator with limits" },
		{ t("sum_("), i(1, "i=0"), t(")^("), i(2, "n"), t(") "), i(3) }
	),
	s(
		{ trig = "prod", desc = "Mathematical product operator with limits" },
		{ t("prod_("), i(1, "i=0"), t(")^("), i(2, "n"), t(") "), i(3) }
	),
	s(
		{ trig = "int", desc = "Definite mathematical integral operator with bounds" },
		{ t("integral_("), i(1, "a"), t(")^("), i(2, "b"), t(") "), i(3) }
	),
	s(
		{ trig = "lim", desc = "Mathematical limit expression target" },
		{ t("lim_("), i(1, "x"), t(" -> "), i(2, "inf"), t(") "), i(3) }
	),
	s({ trig = "sqrt", desc = "Mathematical square root radical function" }, { t("sqrt("), i(1), t(")") }),
	s(
		{ trig = "root", desc = "Mathematical nth-order root function" },
		{ t("root("), i(1, "n"), t(", "), i(2, "x"), t(")") }
	),
	s({ trig = "abs", desc = "Absolute value bracket wrapper" }, { t("|"), i(1), t("|") }),
	s({ trig = "norm", desc = "Mathematical norm bracket wrapper" }, { t("||"), i(1), t("||") }),
	s(
		{ trig = "pdiff", desc = "Partial derivative fractional notation template" },
		{ t("(diff "), i(1, "f"), t(")/(diff "), i(2, "x"), t(")") }
	),
	s(
		{ trig = "diff", desc = "Total derivative fractional notation template" },
		{ t("(d "), i(1, "f"), t(")/(d "), i(2, "x"), t(")") }
	),
	s(
		{ trig = "binom", desc = "Binomial coefficient matrix notation" },
		{ t("binom("), i(1, "n"), t(", "), i(2, "k"), t(")") }
	),
	s({ trig = "ceil", desc = "Mathematical ceiling rounding bracket function" }, { t("ceil("), i(1), t(")") }),
	s({ trig = "floor", desc = "Mathematical floor rounding bracket function" }, { t("floor("), i(1), t(")") }),
	s({ trig = "cases", desc = "Piecewise math function cases container" }, { t("cases("), i(1), t(")") }),

	-- Matrices & Vectors
	s({ trig = "vec", desc = "Vector column array template" }, { t("vec("), i(1), t(")") }),
	s({ trig = "mat", desc = "Generic structural matrix template" }, { t("mat("), i(1), t(")") }),
	s({ trig = "mat2", desc = "Two-by-two square matrix matrix notation template" }, {
		t("mat("),
		i(1, "a"),
		t(", "),
		i(2, "b"),
		t("; "),
		i(3, "c"),
		t(", "),
		i(4, "d"),
		t(")"),
	}),
	s({ trig = "mat3", desc = "Three-by-three square matrix notation template" }, {
		t("mat("),
		i(1, "a"),
		t(", "),
		i(2, "b"),
		t(", "),
		i(3, "c"),
		t("; "),
		i(4, "d"),
		t(", "),
		i(5, "e"),
		t(", "),
		i(6, "f"),
		t("; "),
		i(7, "g"),
		t(", "),
		i(8, "h"),
		t(", "),
		i(9, "i"),
		t(")"),
	}),
	s({ trig = "det", desc = "Matrix determinant operator prefix" }, { t("det "), i(1) }),
	s({ trig = "trace", desc = "Matrix trace operator prefix" }, { t("tr "), i(1) }),
	s({ trig = "transpose", desc = "Matrix transpose mathematical superscript" }, { i(1), t("^T") }),
	s({ trig = "inv", desc = "Matrix inverse mathematical power superscript" }, { i(1), t("^(-1)") }),

	-- Accents & Brackets
	s({ trig = "conj", desc = "Complex conjugate modifier function" }, { t("conj("), i(1), t(")") }),
	s({ trig = "hat", desc = "Hat accent mathematical symbol modifier" }, { t("hat("), i(1), t(")") }),
	s({ trig = "bar", desc = "Overline bar accent mathematical symbol modifier" }, { t("overline("), i(1), t(")") }),
	s({ trig = "tilde", desc = "Tilde accent mathematical symbol modifier" }, { t("tilde("), i(1), t(")") }),
	s({ trig = "dot", desc = "Single dot accent mathematical symbol modifier" }, { t("dot("), i(1), t(")") }),
	s({ trig = "ddot", desc = "Double dot accent mathematical symbol modifier" }, { t("dot.double("), i(1), t(")") }),
	s({ trig = "lr", desc = "Dynamic sizing left-right parentheses wrapper" }, { t("lr("), i(1), t(")") }),
	s({ trig = "lrb", desc = "Dynamic sizing left-right square brackets wrapper" }, { t("lr(["), i(1), t("])") }),
	s({ trig = "lrc", desc = "Dynamic sizing left-right curly braces wrapper" }, { t("lr({"), i(1), t("})") }),
	s({ trig = "set", desc = "Mathematical set notation" }, { t("{ "), i(1), t(" }") }),
	s({ trig = "setb", desc = "Set builder notation with condition" }, { t("{ "), i(1, "x"), t(" in "), i(2, "S"), t(" : "), i(3, "P(x)"), t(" }") }),

	-- Math Symbols, Relations & Arrows
	s({ trig = "inff", desc = "Infinity mathematical symbol" }, { t("infinity") }),
	s({ trig = "nab", desc = "Nabla gradient mathematical operator" }, { t("nabla") }),
	s({ trig = "arr", desc = "Standard math relation arrow direction" }, { t("arrow") }),
	s({ trig = "rarr", desc = "Rightward pointing relation arrow" }, { t("arrow.r") }),
	s({ trig = "larr", desc = "Leftward pointing relation arrow" }, { t("arrow.l") }),
	s({ trig = "uarr", desc = "Upward pointing relation arrow" }, { t("arrow.t") }),
	s({ trig = "darr", desc = "Downward pointing relation arrow" }, { t("arrow.b") }),
	s({ trig = "iff", desc = "If and only if logical equivalence arrow" }, { t("<==>") }),
	s({ trig = "==>", desc = "Logical implication rightward relation arrow" }, { t("==>") }),
	s({ trig = "therefore", desc = "Therefore logical conclusion conclusion symbol" }, { t("therefore") }),
	s({ trig = "because", desc = "Because logical explanation symbol" }, { t("because") }),
	s({ trig = "forall", desc = "For all universal quantifier symbol" }, { t("forall") }),
	s({ trig = "exists", desc = "Exists existential quantifier symbol" }, { t("exists") }),
	s({ trig = "elem", desc = "Element of set membership symbol" }, { t("in") }),
	s({ trig = "notin", desc = "Not an element of set membership negation symbol" }, { t("in.not") }),
	s({ trig = "subs", desc = "Subset inclusion operation relation symbol" }, { t("subset") }),
	s({ trig = "cup", desc = "Union set operation symbol" }, { t("union") }),
	s({ trig = "cap", desc = "Intersection set operation symbol" }, { t("intersection") }),
	s({ trig = "empty", desc = "Empty set null space placeholder symbol" }, { t("nothing") }),
	s({ trig = "neq", desc = "Not equal relation symbol" }, { t("!=") }),
	s({ trig = "leq", desc = "Less than or equal relation symbol" }, { t("<=") }),
	s({ trig = "geq", desc = "Greater than or equal relation symbol" }, { t(">=") }),
	s({ trig = "approx", desc = "Approximately equal relation symbol" }, { t("approx") }),
	s({ trig = "times", desc = "Multiplication cross symbol" }, { t("times") }),
	s({ trig = "cdot", desc = "Center dot multiplication symbol" }, { t("dot.c") }),

	-- Number sets (Blackboard Bold)
	s({ trig = "RR", desc = "Set of real numbers blackboard bold identifier" }, { t("RR") }),
	s({ trig = "add", desc = "Set of real numbers blackboard bold identifier" }, { t("RR") }),
	s({ trig = "NN", desc = "Set of natural numbers blackboard bold identifier" }, { t("NN") }),
	s({ trig = "ZZ", desc = "Set of integers blackboard bold identifier" }, { t("ZZ") }),
	s({ trig = "QQ", desc = "Set of rational numbers blackboard bold identifier" }, { t("QQ") }),
	s({ trig = "CC", desc = "Set of complex numbers blackboard bold identifier" }, { t("CC") }),

	-- Greek lowercase letters
	s({ trig = "aa", desc = "Greek lowercase letter alpha" }, { t("alpha") }),
	s({ trig = "bb", desc = "Greek lowercase letter beta" }, { t("beta") }),
	s({ trig = "gg", desc = "Greek lowercase letter gamma" }, { t("gamma") }),
	s({ trig = "dd", desc = "Greek lowercase letter delta" }, { t("delta") }),
	s({ trig = "ee", desc = "Greek lowercase letter epsilon" }, { t("epsilon") }),
	s({ trig = "th", desc = "Greek lowercase letter theta" }, { t("theta") }),
	s({ trig = "ll", desc = "Greek lowercase letter lambda" }, { t("lambda") }),
	s({ trig = "mm", desc = "Greek lowercase letter mu" }, { t("mu") }),
	s({ trig = "pp", desc = "Greek lowercase letter pi" }, { t("pi") }),
	s({ trig = "ss", desc = "Greek lowercase letter sigma" }, { t("sigma") }),
	s({ trig = "oo", desc = "Greek lowercase letter omega" }, { t("omega") }),
	s({ trig = "ph", desc = "Greek lowercase letter phi" }, { t("phi") }),
	s({ trig = "ps", desc = "Greek lowercase letter psi" }, { t("psi") }),
	s({ trig = "rh", desc = "Greek lowercase letter rho" }, { t("rho") }),
	s({ trig = "ta", desc = "Greek lowercase letter tau" }, { t("tau") }),
})
