#!/usr/bin/env python3

from __future__ import annotations

import argparse
import json
import os
import re
import subprocess
import sys
import textwrap
from pathlib import Path


KIND_LAYOUTS = {
    "layer": Path("modules/features/layers"),
    "feature": Path("modules/features"),
    "host": Path("modules/hosts"),
    "package": Path("modules/packages"),
}

TEMPLATES_INFO = {
    "layer": {
        "basic": "Bare NixOS module registering into a module group (default: shared)",
        "hjem": "Module with user dotfile management via hjem",
        "service": "Module with a systemd user or system service",
        "full": "Comprehensive layer with packages, hjem files, and systemd service",
    },
    "feature": {
        "basic": "Bare feature module",
        "app": "Application feature with system package and hjem config file",
        "service": "Background systemd user service daemon feature",
        "theme": "Theme-integrated feature using config.theme.colors",
    },
    "host": {
        "standard": "Multi-file host directory (default.nix, configuration.nix, _hardware-generated.nix)",
    },
    "package": {
        "shell": "Executable created with pkgs.writeShellApplication (default)",
        "stdenv": "Custom derivation built with pkgs.stdenvNoCC.mkDerivation",
        "python": "Python 3 binary created with pkgs.writers.writePython3Bin",
        "rust": "Rust package built with pkgs.rustPlatform.buildRustPackage",
    },
}

NAME_RE = re.compile(r"^[A-Za-z0-9][A-Za-z0-9_.-]*$")


class Colors:
    GREEN = "\033[32m"
    CYAN = "\033[36m"
    YELLOW = "\033[33m"
    BOLD = "\033[1m"
    RESET = "\033[0m"

    @classmethod
    def enable(cls) -> bool:
        return sys.stdout.isatty() and os.getenv("NO_COLOR") is None


def fmt(text: str, style: str) -> str:
    if Colors.enable():
        return f"{style}{text}{Colors.RESET}"
    return text


def nix_string(value: str) -> str:
    return json.dumps(value)


def git_root() -> Path | None:
    result = subprocess.run(
        ["git", "rev-parse", "--show-toplevel"],
        check=False,
        capture_output=True,
        text=True,
    )
    if result.returncode != 0:
        return None
    return Path(result.stdout.strip())


def host_templates(name: str) -> dict[Path, str]:
    quoted_name = nix_string(name)
    return {
        Path("default.nix"): textwrap.dedent(
            f"""\
            {{ inputs, config, ... }}:
            {{
              flake.nixosConfigurations.{name} = inputs.nixpkgs.lib.nixosSystem {{
                modules = [
                  config.nixos.modules.shared
                  config.nixos.modules.{name}
                ];
              }};
            }}
            """
        ),
        Path("configuration.nix"): textwrap.dedent(
            f"""\
            {{ ... }}:
            {{
              nixos.modules.{name} =
                {{ pkgs, lib, config, ... }}:
                {{
                  imports = [
                    ./_hardware-generated.nix
                  ]
                  ++ lib.optional (builtins.pathExists ./_installer-options.nix) ./_installer-options.nix;

                  networking.hostName = {quoted_name};

                  environment.systemPackages = with pkgs; [
                  ];

                  system.stateVersion = "25.11";
                }};
            }}
            """
        ),
        Path("_hardware-generated.nix"): textwrap.dedent(
            f"""\
            {{ ... }}:
            {{
              # Hardware configuration skeleton for {name}.
              # Copy actual hardware configuration generated by the installer:
              # cp /etc/nixos/hardware-configuration.nix modules/hosts/{name}/_hardware-generated.nix

              boot.loader.limine.enable = true;
              boot.loader.efi.canTouchEfiVariables = true;

              fileSystems."/" = {{
                device = "/dev/disk/by-label/nixos";
                fsType = "ext4";
              }};

              fileSystems."/boot" = {{
                device = "/dev/disk/by-label/EFI";
                fsType = "vfat";
                options = [ "fmask=0077" "dmask=0077" ];
              }};
            }}
            """
        ),
    }


def layer_template(name: str, target: str, tmpl: str) -> str:
    if tmpl == "hjem":
        return textwrap.dedent(
            f"""\
            {{ ... }}:
            {{
              nixos.modules.{target} =
                {{ pkgs, lib, config, ... }}:
                {{
                  hjem.users.${{config.username}}.files = {{
                    ".config/{name}/config" = {{
                      text = ''
                        # Configuration for {name}
                      '';
                    }};
                  }};
                }};
            }}
            """
        )
    if tmpl == "service":
        return textwrap.dedent(
            f"""\
            {{ ... }}:
            {{
              nixos.modules.{target} =
                {{ pkgs, lib, config, ... }}:
                {{
                  systemd.user.services.{name} = {{
                    description = "{name} user service";
                    wantedBy = [ "graphical-session.target" ];
                    after = [ "graphical-session.target" ];
                    partOf = [ "graphical-session.target" ];
                    serviceConfig = {{
                      ExecStart = "${{pkgs.{name}}}/bin/{name}";
                      Restart = "on-failure";
                      RestartSec = 2;
                    }};
                  }};
                }};
            }}
            """
        )
    if tmpl == "full":
        return textwrap.dedent(
            f"""\
            {{ ... }}:
            {{
              nixos.modules.{target} =
                {{ pkgs, lib, config, ... }}:
                {{
                  environment.systemPackages = with pkgs; [
                    {name}
                  ];

                  hjem.users.${{config.username}}.files = {{
                    ".config/{name}/config" = {{
                      text = ''
                        # Configuration for {name}
                      '';
                    }};
                  }};

                  systemd.user.services.{name} = {{
                    description = "{name} daemon service";
                    wantedBy = [ "graphical-session.target" ];
                    after = [ "graphical-session.target" ];
                    serviceConfig = {{
                      ExecStart = "${{pkgs.{name}}}/bin/{name}";
                      Restart = "on-failure";
                      RestartSec = 2;
                    }};
                  }};
                }};
            }}
            """
        )
    # Default: basic
    return textwrap.dedent(
        f"""\
        {{ ... }}:
        {{
          nixos.modules.{target} =
            {{ pkgs, lib, config, ... }}:
            {{
              environment.systemPackages = with pkgs; [
              ];
            }};
        }}
        """
    )


def feature_template(name: str, target: str, tmpl: str) -> str:
    if tmpl == "app":
        return textwrap.dedent(
            f"""\
            {{ ... }}:
            {{
              nixos.modules.{target} =
                {{ pkgs, lib, config, ... }}:
                {{
                  environment.systemPackages = with pkgs; [
                    {name}
                  ];

                  hjem.users.${{config.username}}.files = {{
                    ".config/{name}/settings.json" = {{
                      text = ''
                        {{}}
                      '';
                    }};
                  }};
                }};
            }}
            """
        )
    if tmpl == "service":
        return textwrap.dedent(
            f"""\
            {{ ... }}:
            {{
              nixos.modules.{target} =
                {{ pkgs, lib, config, ... }}:
                {{
                  systemd.user.services.{name} = {{
                    description = "{name} service daemon";
                    wantedBy = [ "graphical-session.target" ];
                    after = [ "graphical-session.target" ];
                    serviceConfig = {{
                      ExecStart = "${{pkgs.{name}}}/bin/{name}";
                      Restart = "on-failure";
                      RestartSec = 2;
                    }};
                  }};
                }};
            }}
            """
        )
    if tmpl == "theme":
        return textwrap.dedent(
            f"""\
            {{ ... }}:
            {{
              nixos.modules.{target} =
                {{ pkgs, lib, config, ... }}:
                let
                  c = config.theme.colors;
                in
                {{
                  hjem.users.${{config.username}}.files = {{
                    ".config/{name}/theme.toml" = {{
                      text = ''
                        [colors]
                        background = "#${{c.bg}}"
                        foreground = "#${{c.fg}}"
                        accent = "#${{c.accent}}"
                      '';
                    }};
                  }};
                }};
            }}
            """
        )
    # Default: basic
    return textwrap.dedent(
        f"""\
        {{ ... }}:
        {{
          nixos.modules.{target} =
            {{ pkgs, lib, config, ... }}:
            {{
              environment.systemPackages = with pkgs; [
              ];
            }};
        }}
        """
    )


def package_template(name: str, tmpl: str) -> str:
    quoted_name = nix_string(name)
    if tmpl == "stdenv":
        return textwrap.dedent(
            f"""\
            {{ ... }}:
            {{
              perSystem =
                {{ pkgs, lib, ... }}:
                {{
                  packages.{name} = pkgs.stdenvNoCC.mkDerivation {{
                    pname = {quoted_name};
                    version = "0.1.0";
                    src = ./.;

                    dontBuild = true;

                    installPhase = ''
                      runHook preInstall
                      install -Dm755 {name}.sh "$out/bin/{name}"
                      runHook postInstall
                    '';

                    meta = {{
                      description = "{name} package";
                      license = lib.licenses.mit;
                      mainProgram = {quoted_name};
                    }};
                  }};
                }};
            }}
            """
        )
    if tmpl == "python":
        return textwrap.dedent(
            f"""\
            {{ ... }}:
            {{
              perSystem =
                {{ pkgs, ... }}:
                {{
                  packages.{name} = pkgs.writers.writePython3Bin {quoted_name} {{
                    libraries = with pkgs.python3Packages; [ ];
                  }} ''
                    import sys

                    def main():
                        print("Running {name}...")

                    if __name__ == "__main__":
                        main()
                  '';
                }};
            }}
            """
        )
    if tmpl == "rust":
        return textwrap.dedent(
            f"""\
            {{ ... }}:
            {{
              perSystem =
                {{ pkgs, lib, ... }}:
                {{
                  packages.{name} = pkgs.rustPlatform.buildRustPackage {{
                    pname = {quoted_name};
                    version = "0.1.0";
                    src = ./.;
                    cargoHash = lib.fakeHash;

                    meta = {{
                      description = "{name} rust application";
                      license = lib.licenses.mit;
                      mainProgram = {quoted_name};
                    }};
                  }};
                }};
            }}
            """
        )
    # Default: shell
    return textwrap.dedent(
        f"""\
        {{ ... }}:
        {{
          perSystem =
            {{ pkgs, ... }}:
            {{
              packages.{name} = pkgs.writeShellApplication {{
                name = {quoted_name};
                runtimeInputs = with pkgs; [ ];
                text = ''
                  echo "TODO: implement {name}"
                '';
              }};
            }};
        }}
        """
    )


def planned_files(
    kind: str, name: str, target: str, tmpl: str, multifile: bool
) -> dict[Path, str]:
    if kind == "host":
        return host_templates(name)

    filename = Path("default.nix") if multifile else Path(f"{name}.nix")
    if kind == "layer":
        content = layer_template(name, target, tmpl)
    elif kind == "feature":
        content = feature_template(name, target, tmpl)
    elif kind == "package":
        content = package_template(name, tmpl)
    else:
        raise ValueError(f"Unsupported kind: {kind}")

    return {filename: content}


def update_module_groups(root: Path, host_name: str) -> bool:
    groups_path = root / "modules/module-groups.nix"
    if not groups_path.exists():
        return False

    content = groups_path.read_text(encoding="utf-8")
    if f"{host_name} =" in content:
        return False

    snippet = textwrap.dedent(
        f"""\
            {host_name} = lib.mkOption {{
              type = lib.types.deferredModule;
              default = {{ }};
              description = "{host_name} host specific configuration.";
            }};
        """
    )

    idx = content.rfind("  };")
    if idx != -1:
        new_content = content[:idx] + snippet + content[idx:]
        groups_path.write_text(new_content, encoding="utf-8")
        return True

    return False


def write_file(path: Path, content: str) -> None:
    if path.exists():
        raise FileExistsError(f"Refusing to overwrite existing path: {path}")
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content.rstrip() + "\n", encoding="utf-8")


def stage(paths: list[Path], root: Path) -> None:
    subprocess.run(
        ["git", "add", "--", *[str(path.relative_to(root)) for path in paths]],
        check=True,
        cwd=root,
    )


def print_templates_help() -> None:
    print(fmt("Available Boilerplate Kinds & Templates:", Colors.BOLD))
    print()
    for kind, tmpls in TEMPLATES_INFO.items():
        print(f"  {fmt(kind, Colors.CYAN)} (target directory: modules/{kind}s/):")
        for tmpl, desc in tmpls.items():
            print(f"    - {fmt(tmpl, Colors.GREEN)}: {desc}")
        print()


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Generate Nix boilerplate modules for NixConfig",
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument(
        "kind",
        nargs="?",
        choices=sorted(KIND_LAYOUTS),
        help="Kind of module to generate (layer, feature, host, package)",
    )
    parser.add_argument(
        "name",
        nargs="?",
        help="Name of the module or package to create",
    )
    parser.add_argument(
        "-t",
        "--template",
        default="basic",
        help="Template variant (e.g. basic, hjem, service, app, theme, shell, stdenv, python, rust)",
    )
    parser.add_argument(
        "--target",
        default="shared",
        help="Target module group (default: shared, desktop, laptop)",
    )
    parser.add_argument(
        "--update-groups",
        action="store_true",
        help="Automatically register host in modules/module-groups.nix when creating a host",
    )
    parser.add_argument(
        "-l",
        "--list-templates",
        action="store_true",
        help="List all available module kinds and templates",
    )
    parser.add_argument(
        "--no-git-stage", action="store_true", help="Do not stage created files in git"
    )
    parser.add_argument(
        "--dry-run", action="store_true", help="Print planned files without creating them"
    )
    parser.add_argument(
        "--multifile",
        action="store_true",
        help="Create <name>/default.nix instead of <name>.nix",
    )

    args = parser.parse_args()
    if args.list_templates:
        print_templates_help()
        sys.exit(0)

    if not args.kind or not args.name:
        parser.print_help()
        print()
        print(fmt("Error: missing required arguments 'kind' and 'name'.", Colors.YELLOW))
        print("Run with -l/--list-templates to see available templates.")
        sys.exit(2)

    return args


def main() -> int:
    args = parse_args()

    if not NAME_RE.fullmatch(args.name):
        print(
            fmt("Error: name must match ^[A-Za-z0-9][A-Za-z0-9_.-]*$", Colors.YELLOW),
            file=sys.stderr,
        )
        return 2

    root = git_root()
    if root is None:
        if args.dry_run or args.no_git_stage:
            root = Path.cwd()
        else:
            print("Error: not inside a git repository; use --no-git-stage", file=sys.stderr)
            return 2

    files = planned_files(args.kind, args.name, args.target, args.template, args.multifile)
    base = root / KIND_LAYOUTS[args.kind]

    # For hosts or multifile features/packages, create a subdirectory
    if args.kind == "host" or args.multifile:
        target_base = base / args.name
    else:
        target_base = base

    targets = [target_base / rel for rel in files]

    if args.dry_run:
        print(fmt("Dry run: no files will be created", Colors.CYAN))
        for target in targets:
            print(f"  {target.relative_to(root)}")
        return 0

    try:
        for rel_path, content in files.items():
            write_file(target_base / rel_path, content)
    except FileExistsError as err:
        print(fmt(str(err), Colors.YELLOW), file=sys.stderr)
        return 1

    updated_groups = False
    if args.kind == "host":
        if args.update_groups or True: # Automatically attempt to update module-groups.nix for host creation
            updated_groups = update_module_groups(root, args.name)
            if updated_groups and not args.no_git_stage:
                stage([root / "modules/module-groups.nix"], root)

    if not args.no_git_stage:
        stage(targets, root)

    print(fmt("Created files successfully:", Colors.GREEN))
    for target in targets:
        print(f"  {target.relative_to(root)}")

    if updated_groups:
        print(fmt("  modules/module-groups.nix (updated host options)", Colors.CYAN))

    if args.kind == "host" and not updated_groups:
        print()
        print(fmt("Next Steps:", Colors.BOLD))
        print(f"  Remember to declare option `options.nixos.modules.{args.name}` in modules/module-groups.nix")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
